version: '3.8'

services:
  # --- HADOOP MASTER NODE ---
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    tty: true # Keeps the container running
    stdin_open: true # Allows interaction if needed (similar to -it)
    volumes:
      # Maps your local ~/Documents/hadoop_project/ to /shared_volume in the container
      - ~/Documents/hadoop_project/:/shared_volume
    ports:
      # Core Hadoop/Spark/Jupyter/App ports
      - "9870:9870"   # HDFS NameNode Web UI
      - "8088:8088"   # YARN ResourceManager Web UI
      - "7077:7077"   # Spark Master Web UI (and driver port)
      - "19888:19888" # MapReduce JobHistory Server Web UI
      - "8081:8081"   # Default Jupyter port (configurable)
      - "9000:9000"   # Default HDFS port (core-site.xml)
    networks:
      - hadoop_network
    
  # --- HADOOP SLAVE NODE 1 ---
  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    tty: true
    stdin_open: true
    ports:
      # Maps local port 8040 to the slave's internal NodeManager port 8042
      - "8040:8042"
    networks:
      - hadoop_network

  # --- HADOOP SLAVE NODE 2 ---
  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    tty: true
    stdin_open: true
    ports:
      # Maps local port 8041 to the slave's internal NodeManager port 8042
      - "8041:8042"
    networks:
      - hadoop_network

# --- NETWORK DEFINITION ---
networks:
  hadoop_network:
    name: hadoop